# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.13'
steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- task: AzureKeyVault@1
  inputs:
    ConnectedServiceName: 'Free Trial(843929f7-f9ba-47fe-8b5f-f02d3cffaba1)'
    KeyVaultName: 'Fermitools-Vault'
    SecretsFilter: 'Jasercion-Anaconda-Api'

- bash: conda create --yes --quiet --name py2_build -c conda-forge python=2.7
  displayName: Create Anaconda environment
  
- bash: |
    source activate py2_build
    conda install --yes -c conda-forge conda-build anaconda-client
    source deactivate
  displayName: Set up environment for build

- bash: |
    conda config --add channels https://conda.anaconda.org/t/$Jasercion-Anaconda-Api/jasercion/label/dev
    conda config --set anaconda_upload yes
  displayName: Set up upload configuration

- bash: |
    source activate py2_build
    conda build --python=2.7 -c conda-forge/label/cf201901 -c fermi .
  displayName: Launch build

- bash: | 
    source deactivate
    conda create --yes --quiet --use-local --name test -c conda-forge/label/cf201901 -c fermi -c jasercion/label/dev fermitools fermitools-test-scripts
    mkdir test
    cd test
  displayName: Set up test environment

- bash: |
    source activate test
    ST-unit-test --bit64
  displayName: Run unit tests
